### ISSUE TITLE
Getting dimension error for models when running the evalutaion script for NCBID

### ISSUE THREAD

**Issue by llangnickel** [IBM/aihn-ucsd#2] opened 2019-05-22 08:43 UTC
after doing all the steps described in the README for downloading and preprocessing the data, I get the following error for the NCBID model:  
  
RuntimeError: Error(s) in loading state_dict for NormalizationModel:  
        While copying the parameter named "phrase_model.embeddings.weight", whose   dimensions in the model are torch.Size([23455, 200]) and whose dimensions in the checkpoint   are torch.Size([27131, 200]).  
  
I tried to train the model again from scratch and evaluate it afterwards which works but I was not able to reproduce the results written in the paper.  
Any ideas how to fix this?

**Comment by dwright37** [comment] 2019-05-29 19:47
Thanks for reaching out. Unfortunately I don't know what the issue is from that alone, the final vocabulary size is smaller than it should be so it could be a matter of not formatting the traindev and test data files correctly or downloading the mention only version as opposed to the complete version. To check if its a data issue you could try is using the data from TaggerOne (in the TaggerOne download under data/NCBID/Corpus.txt) by changing lines 7 and 8 of generate_data.sh to the following:

traindev_file=$TAGGER_ONE_DIR/data/NCBID/Corpus.txt
test_file=$TAGGER_ONE_DIR/data/NCBID/Corpus.txt

Make sure to pull again before trying this. If it still doesn't work then it would either be the concept dict is wrong or the pretrained embeddings are wrong. Hope that helps, let me know if you still have issues

**Comment by llangnickel** [comment] 2019-06-04 08:39
Thank you very much; it really seemed to be a formatting error. After downloading and combining the files now again, I got it running. 

Maybe another hint: 
I needed to change line 132 in the generate_data.py script to get the preprocessing working. 
I changed it to: 

with open(vocabFileName, 'w', encoding='utf-8') as f:

Otherwise, I got a UnicodeDecode Error (using a linux machine).

**Comment by dwright37** [comment] 2019-06-04 23:40
Great! And good catch, I updated the data generation script (6c31fcf). Closing this issue as resolved.

**Closed as completed by dwright37** 2019-06-04 23:40 UTC
